
services:
    app:
        image: python:3.9-alphine
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - .:/core
        depends_on: 
            - database

    database:
        image: postgres:9.9-alphine
        restart: always
        ports:
          - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    
